### ISSUE TITLE
Select by typing in SelectMenu (like native menus)

### ISSUE THREAD

**Issue by fregante** [primer/components#1022]
What do you think about supporting navigation by typing as well, as available on macOS (and presumably on other OSes as well). Example when pressing <kbd>g</kbd>:

![](https://user-images.githubusercontent.com/1402241/100029978-18e7aa00-2db8-11eb-88fd-07eb1d45fc05.gif)[](https://github.com/sindresorhus/refined-github/issues/3761)

This behavior also exists in regular `<select>` elements in the browser, but not here.

**Comment by emplums** [comment]
This will be addressed in the Overlay epic 👍 Going to close this for now as it's captured in an issue in another repo :)

**Comment by fregante** [comment]
Great to hear! Is it public? Got a link so I can keep track of it?

**Comment by emplums** [comment]
@fregante We don't quite have a public issue for it yet (it's in another internal repo) but I believe @smockle will be creating issues in this repo as we move forward on the project! We will be shipping a whole new overlay system that incorporates SelectMenus, Dialogs, etc and will be doing a visual refresh at that time as well!
