### ISSUE TITLE
ActionMenu

### ISSUE THREAD

**Issue by smockle** [primer/components#1069]
Requires #1064 and https://github.com/primer/components/issues/1056

## Description
Action menus are used for disambiguation, navigation, or to display secondary options. They appear when users interact with buttons, actions, or other controls.

A menu is a list of options presented to the user on a Popover.

Use action menus to present multiple actions, when a source’s (e.g. a button’s) single action would be ambiguous otherwise.

**List options according to how frequent they're used**. Don’t make users scan through a long list of disorganized options. To help users focus on what's relevant, place the options used most often at the top.

**Limit the number of options within an action menu**. Don’t overwhelm users with too many items. Keep the menu length manageable by including fewer than 10 options. Remember action menus may get bigger in mobile or touch devices.

All menu items trigger an action.

**Menus can use a Bottom sheet mobile variant** that provides room for additional items, longer descriptions, and iconography.

**Keep action menu overlays simple**. Don't use overlay headers and overlay footers alongside action menus.

## Resources
Figma:
Prototype:

## Screenshot
![actionmenu](https://user-images.githubusercontent.com/3104489/108855015-80c7af80-75b6-11eb-9f14-3afef856ba04.png)

#### Behaviors

An ActionMenu component renders an ActionList containing ActionMenuListItems into a Popover.

ActionMenus should have the [menu](https://w3c.github.io/aria/#menu) role.

#### Behaviors

An ActionMenuListItem component could be built on the ActionListItem component, to reduce props API surface area (i.e. so library consumers don’t need to use ActionListItem directly).

ActionMenuListItems should have the [menuitem](https://w3c.github.io/aria/#menuitem) role.

#### Props

name: `type` (note: as noted in [ActionListItem](https://github.com/primer/components/issues/1056), `variant` would be consistent with Primer’s existing prop naming)
type: `"default" | "danger"`
default: `"default"`
description: Defines the list item type. (Passed through to ActionListItem.)

-----

name: `leadingVisual`
type: `React.ReactElement`
description: An optional visual to accompany the list item. It supports octicons, avatars, or other custom elements. (Passed through to ActionListItem.)

-----

name: `text`
type: `string`
description: The primary text in the list item. Use sentence case. (Passed through to ActionListItem.)

-----

name: `description`
type: `string?`
description: A quick description of the list item. (Passed through to ActionListItem.)

-----

name: `descriptionType`
type: `"inline" | "block"`
description: Defines how the description text will be placed in the list item. An inline description appears adjacent to the text prop, while block places it below in a new line. (Passed through to ActionListItem.)

-----

name: `auxiliaryText`
type: `string`
description: An optional space for auxiliary text at the end of the list item. May be used to render keyboard shortcuts. (Passed through to ActionListItem.)

When rendering keyboard shortcuts, use the system default characters. On macOS, a keyboard shortcut may look like <kbd>⌘S</kbd>. On Windows, <kbd>Ctrl+S</kbd>.

macOS: <kbd>⌘</kbd>, <kbd>⌥</kbd>, <kbd>⇧</kbd>, <kbd>⌃</kbd>
Windows: <kbd>Ctrl</kbd>, <kbd>Shift</kbd>, <kbd>Alt</kbd>

-----

name: `auxiliaryIcon`
type: `Icon`
description: An optional space for an auxiliary icon at the end of the list item. (Passed through to ActionListItem.)

**Comment by VanAnderson** [comment]
@vdepizzol quick question - are there any examples of how auxilaryText and auxilaryIcon might be used together? Will it always be one or the other? Should they have a margin between them? 

(see 'Delete' with TrashIcon and auxilaryText):

![image](https://user-images.githubusercontent.com/16739070/114611614-d8090880-9c66-11eb-800e-ad62fe4f01d2.png)

**Comment by vdepizzol** [comment]
> @vdepizzol quick question - are there any examples of how auxilaryText and auxilaryIcon might be used together? Will it always be one or the other? Should they have a margin between them?

@VanAnderson thanks for asking! I think that's not a common scenario, but it should still be supported. In the example above, the trash icon should be a `leadingVisual` instead. But for other cases, the icon should be closer to the edge, and both right-aligned elements should be 8px apart (like the other elements in the actionList item)

Here's a visual example of a case that could use it (the purple border shows the edge of the ActionList item):
> ![Screen Shot 2021-04-13 at 13 00 04](https://user-images.githubusercontent.com/293280/114613450-367aba80-9c58-11eb-9078-dab2357e5d7c.png)

Regarding the naming, we talked about using `trailingText` and `trailingIcon` to identify the right-aligned items: https://github.slack.com/archives/C01LU5SGQNR/p1617402756067600.

Thanks!

**Comment by smockle** [comment]
Props suggested by issues in other GitHub repos:

* To support usage as a controlled component, add props analogous to `ActionMenus`’s internal [`open`/`setOpen` state](https://github.com/primer/components/blob/ff6e266f46508ae85735a21a4b363ce2fcbc2623/src/DropdownMenu/DropdownMenu.tsx#L43)

* Add props for `onOpen` and `onClose` callback functions, and invoke them when `ActionMenus`’s `Overlay` opens or closes, respectively.
