### ISSUE TITLE
Document dependencies argument on `useAnchoredPosition` hook

### ISSUE THREAD

**Issue by emplums** [primer/components#1120]
Just noticed that the docs has a section for the `UseAnchoredPositionSettings interface`, but doesn't go into detail on what should be provided for the `dependencies` argument or provide a code example. It isn't clear that you are meant to pass a `React.DependencyList` to this argument.

**Comment by T-Hugs** [comment]
Fixed in https://github.com/primer/components/commit/154cb5f946fbe146a7fb9cec8e316eac1d8994ea
