### ISSUE TITLE
Overlay Animation Causes Overflow

### ISSUE THREAD

**Issue by dgreif** [primer/components#1231]
**Describe the bug**
All components built with `Overlay` can cause their parent container to overflow and show scrollbars for a second while the `Overlay` performs a slide-up animation after it is opened.  This happens when the overlay is placed such that it can _fit_ between its anchor and the bottom of the view port, but the slide-up animation cause it to transition from a placement that is _outside_ the dimensions of the viewport.

**Proposed Solution**
We could account for the distance of the slide-up animation when calculating the placement of the overlay.  If it won't fit below the anchor if you consider overlay height + transition height, then it needs to be placed elsewhere. 

Alternatively, we could still place the overlay below the anchor, but shorten or skip the slide-up if there isn't room for it.

Open to other suggestions @vdepizzol 

**To Reproduce**
1. Go to the DropdownMenu story in storybook
2. Adjust the Actions panel height so that there is _just_ enough room for the DropdownMenu to open below the button
3. Open the DropdownMenu
4. Note the scroll bar flicker in and out on the right

**Expected behavior**
Overlay animation should not cause temporary overflow

**Screenshots**
![CleanShot 2021-05-17 at 09 30 17](https://user-images.githubusercontent.com/3026298/118524191-bdf19880-b6f2-11eb-9b30-f404f39fc63f.gif)

**Comment by vdepizzol** [comment]
@dgreif thanks for writing this! ✨ 

I wonder if we can mitigate this entirely by implementing the full animation plan we had where the sliding transition is rendered depending on which `outside-*` anchor side is used. This means we can have a visual connection between the `source` and the overlay. Similar to how select menu handles it in production:

> ![selectMenu transition](https://user-images.githubusercontent.com/293280/118552329-a8409b00-b713-11eb-93e3-76c299a421c4.gif)

In your example above, `outside-bottom` would animate _from top to bottom_, while something like `outside-right` would follow the same animation style, being `from left to right` and always coming from the `source`. I guess using it that way the overlay wouldn't overflow?

| `outside-bottom` example | `outside-right` example |
|--------|--------|
| ![outside-bottom_](https://user-images.githubusercontent.com/293280/118553719-8a743580-b715-11eb-9e36-71cedbbc826f.gif) | ![outside-right](https://user-images.githubusercontent.com/293280/118553728-8ea05300-b715-11eb-8cac-7650d995f3f8.gif) |

**Comment by dgreif** [comment]
Yes, this looks like a great solution!  I didn't realize that was part of the original design, but it makes perfect sense and would fix the overflow issue.  Thanks @vdepizzol!

**Comment by vdepizzol** [comment]
💖 💖 💖
