### ISSUE TITLE
Where are the Breakpoints?

### ISSUE THREAD

**Issue by Moatezz** [primer/components#1234]
Hi, 
I should be able to use some kind of media query, like in system props I should be able to pass a some sort of  a trinary operator that determines which value to output depending on the breakpoint I Specified.
Ex: `<Box mx={{"sm": 10}, 25} >//content </ Box>`  Something like that.
Does it or an alternative solution   exists?

**Comment by dbolkensteyn** [comment]
`mx`  can take a single value for all breakpoints or an array of values for each breakpoint (and upwards):

```
<Box mx={[10, 25]} >//content</ Box>
```

Here it is in the doc: https://primer.style/components/core-concepts#responsive-props

**Comment by Moatezz** [comment]
thanks you, you just made my day dude
