### ISSUE TITLE
List items without leading visuals can be misaligned with items with leading visuals

### ISSUE THREAD

**Issue by dmarcey** [primer/components#1237]
From `Single Select List` story

![image](https://user-images.githubusercontent.com/5487287/118874231-a82dd000-b8b8-11eb-8e93-1ef7538bb16b.png)

The leading visual elements for items without a checkmark have a style to set their width to `width: 16px`, but their computed widths are something like `13.8125px`.

I believe that either changing `width: 16px` to `min-width: 16px;` and `max-width: 16px` or adding a `flex-shrink: 0px` to the base visual container styles would fix the issue. 🤷

**Comment by dgreif** [comment]
Fixed in #1240
