### ISSUE TITLE
Overlay component box shadows in dark and dimmed modes

### ISSUE THREAD

**Issue by pmarsceill** [primer/components#1278]
**Describe the bug**
Using the overlay component in dark and dimmed mode doesn't adjust the box shadow to the proper values. On Dotcom, we use different box shadows for dark modes:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/896475/121066651-1cf97900-c798-11eb-8a7e-e403872d4b91.png">

Currently PRC uses the same shadows for dark and light modes which makes the dropdown look like it's foggy and sad in dark modes:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/896475/121067078-9ee9a200-c798-11eb-9926-0c7eeb136494.png">

**Note:** As this is a public repo, please be careful not to include details or screenshots from unreleased GitHub products or features. In most cases, a good bug report should be able to describe the new component without including business logic or feature details, but if you must discuss context relating to an unreleased feature, please open an issue in the private [Design Systems repo](https://github.com/github/design-systems/issues/new/choose) and link to it here.

**To Reproduce**
Use an overlay component in dark mode

**Expected behavior**
Same dropshadow for dark mode as we use on Dotcom 

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Comment by bscofield** [comment]
https://github.com/primer/components/pull/1279
