### ISSUE TITLE
Header.Item mr value being ignored

### ISSUE THREAD

**Issue by confused-Techie** [primer/components#1339]
**Describe the bug**
While following the Docs I created a Header.Item component, and attempted to use the mr value to have the last item right aligned, but that value doesn't seem to change anything as of now.

**To Reproduce**
I am working in Nextjs to create the website, and have imported the Primer Components via npm. The below code is of my navbar.js component which is imported into a layout.js component, and finally displayed on a page, which for testing is index.js.

````
// This code has been simplified from the original.
import { Header, Avatar } from '@primer/components'

function Navbar() {
  return (
    <>
      <Header>
        <Header.Item>
          <Header.Link href="#">Dashboard</Header.Link>
        </Header.Item>
        <Header.Item mr={0}>
          <Avatar src="https://avatars.githubusercontent.com/github" />
        </Header.Item>
      </Header>
    </>
  )
}
````
I have also attempted defining this value through the sx prop
````
<Header.Item sx={{
  '> *': {
    mr: 0
  }
}}> 
<Avatar src="https://avatars.githubusercontent.com/github" />
</Header.Item>
````
Still somewhat new to React, so if helpful here is my layout.js.

````
import { Box, Flex, ThemeProvider } from '@primer/components'
import Navbar from './navbar'

export default function Layout({ children }) {
  return (
    <>
      <ThemeProvider>
        <Navbar />
          <main>{children}</main>
        </ThemeProvider>
    </>
  )
}
````

**Expected behavior**
The expected behavior would be for the Avatar component to be properly right aligned with 0 margin.
Instead of it continuing to be aligned in the default location.

**Desktop (please complete the following information):**
 - OS: Windows 10 Desktop
 - Browser: Chrome
 - Version: 91.0.4472164
 - Framework: Nextjs

EDIT: Must've missed the browser version on the original post. Added that in.

**Comment by pavelkeyzik** [comment]
I'm not really sure but I think that you missed `full` attribute in your first Header.Item. In your case it will be something like this:

```jsx
<Header>
  <Header.Item full> // <-- Just set prop full to true
    <Header.Link href="#">Dashboard</Header.Link>
  </Header.Item>
  <Header.Item mr={0}>
    <Avatar src="https://avatars.githubusercontent.com/github" />
  </Header.Item>
</Header>
```

**Comment by confused-Techie** [comment]
> I'm not really sure but I think that you missed `full` attribute in your first Header.Item. In your case it will be something like this:
> 
> ```js
> <Header>
>   <Header.Item full> // <-- Just set prop full to true
>     <Header.Link href="#">Dashboard</Header.Link>
>   </Header.Item>
>   <Header.Item mr={0}>
>     <Avatar src="https://avatars.githubusercontent.com/github" />
>   </Header.Item>
> </Header>
> ```

I'll go ahead and give that a try in a bit, thanks for the suggestion

**Comment by confused-Techie** [comment]
> I'm not really sure but I think that you missed `full` attribute in your first Header.Item. In your case it will be something like this:
> 
> ```js
> <Header>
>   <Header.Item full> // <-- Just set prop full to true
>     <Header.Link href="#">Dashboard</Header.Link>
>   </Header.Item>
>   <Header.Item mr={0}>
>     <Avatar src="https://avatars.githubusercontent.com/github" />
>   </Header.Item>
> </Header>
> ```

Yup that seemed to do it, whatever Item is meant to be the last left aligning item needs the full attribute. Thanks for you help!
