### ISSUE TITLE
Heading example fontSize being overridden by markdown styles

### ISSUE THREAD

**Issue by emplums** [primer/components#251]
All of the fontSizes are the same in the example and are being overridden by the `.markdown-body h1` rule
![image](https://user-images.githubusercontent.com/8960591/45503797-cf619600-b73c-11e8-82cf-971ac083f64a.png)

**Comment by broccolini** [comment]
I also noticed that the `is` prop is overriding visual styles rather than just changing the html tag that's rendered, is that due to the same Markdown issue? I hope so or it's a bigger problem 😬

**Comment by emplums** [comment]
Addressed in gatsby-theme-primer
