### ISSUE TITLE
test paperclip figma

### ISSUE THREAD

**Issue by emplums** [primer/components#371]
test https://www.figma.com/file/cIjbmcnlSJpkGPftyFzpykP2/Octicons?node-id=0%3A1

**Comment by emplums** [comment]
test public link https://www.figma.com/file/Y21ABWzzk2GSmO6WXThAgUO4/Untitled

**Comment by gimenete** [comment]
test public link https://www.figma.com/file/Y21ABWzzk2GSmO6WXThAgUO4/Untitled

**Comment by tcbyrd** [comment]
Testing again: https://www.figma.com/file/Y21ABWzzk2GSmO6WXThAgUO4/Untitled

**Comment by tcbyrd** [comment]
Testing private link: https://www.figma.com/file/cIjbmcnlSJpkGPftyFzpykP2/Octicons?node-id=0%3A1

**Comment by gimenete** [comment]
Test private link: https://www.figma.com/file/Vv1TJiAJmUUwLXoSsa9Y4qa0/mashed

**Comment by gimenete** [comment]
test https://www.figma.com/file/Y21ABWzzk2GSmO6WXThAgUO4/Untitled?node-id=0%3A1

**Comment by gimenete** [comment]
Another test https://www.figma.com/file/Vv1TJiAJmUUwLXoSsa9Y4qa0/mashed
