### ISSUE TITLE
`styles.order` should be on `FLEX_ITEM`

### ISSUE THREAD

**Issue by chrislopresto** [primer/components#405]
Hey folks. Thanks for the fine work and for open-sourcing it as MIT.

When perusing your source for inspiration for our design system, I noticed that `styles.order` was included on the `FLEX_CONTAINER` constant rather than the `FLEX_ITEM` constant.

https://github.com/primer/components/blob/204f45402fad9d8d1a3e6525fbf9881bc9c51980/src/constants.js#L50-L65

It probably belongs on `FLEX_ITEM`, right? I figured I'd open an issue to a) mention it in case you weren't aware and b) send some drive-by thanks.

Thanks! 🎉

**Comment by emplums** [comment]
Oh hey nice catch @chrislopresto! I'll fix that tomorrow :) Thanks for the heads up!
