### ISSUE TITLE
CircleOcticon issues

### ISSUE THREAD

**Issue by emplums** [primer/components#415]
CircleOcticon should account for different widths & heights - right now you can only pass one number to `size`. We should expand the size prop to take an array `[12,16]` for width and height sizes. 

For example, the icon in the merge box has a width/height of 12 & 16, so right now there's no way of creating an icon with differing widths & heights. This might need to be fixed on the Octicon library's end as well.

We should also allow the user to set a different size for the circle around the Octicon. So maybe a `size` prop and an `iconSize` prop.

**Comment by ashygee** [comment]
@emplums I think this would be a good case for standardizing the Octicons to a 16x16 grid. This is something I was briefly working on with @jonrohan but since it's such a large change we should do some extensive testing before releasing.

**Comment by emplums** [comment]
Ah ok! I think if we are planning on standardizing Octicons to a 16x16 grid it might not make sense to make this change here for now!
