### ISSUE TITLE
Hover state of disabled buttons show undisabled colors

### ISSUE THREAD

**Issue by gc** [primer/components#428]
Expected: https://styleguide.github.com/primer/components/buttons/#disabled-state

Actual: https://primer.style/components/docs/Button

Adding a `disabled` prop to each button in the second link shows that the buttons show their undisabled colors on hover rather than the expected colors shown in the first link.

If anyone is looking into this, for convenience here's the link to the Button component: https://github.com/primer/components/blob/master/src/Button.js - I had a look but I'm not sure how to fix it.

**Comment by emplums** [comment]
Thanks for the heads up @gc! 🙌 Fixing this in #423

**Comment by colebemis** [comment]
@emplums Should this be closed now?

**Comment by gc** [comment]
They seem to work as expected, now, thanks!
