### ISSUE TITLE
Additional Props

### ISSUE THREAD

**Issue by emplums** [primer/components#432]
- add BorderRadius to `Box`
- add textAlign to `Text`
- consider adding wrapping props to `Text`

**Comment by zbeyens** [comment]
Can you add `LAYOUT` system props to `Flex`? In one case, I can't set the height to `50%`, even with a parent Box setting the height, the Flex component is not taking the height of the Box (when `flex-direction: column`) but the height of the content.

**Comment by emplums** [comment]
- `BorderRadius` should stay in Border Box
- textAlign now exists in `Text`
- Flex now has the `LAYOUT` props, (it's extending Box)

Going to add the `whiteSpace` prop to `Text`

**Comment by emplums** [comment]
Addressed in #504
