### ISSUE TITLE
Doc landing page doesn't mention React

### ISSUE THREAD

**Issue by ungoldman** [primer/components#434]
Hello!

I was perusing your docs and noticed the components section -- however when visiting https://primer.style/components it took me a minute to figure out that these were specifically React components, since the word `React` is not mentioned anywhere on this page!

I think adding some introductory text explaining what kind of components these are might help newcomers better understand the project when visiting https://primer.style/components. There are quite a lot of different flavors of components out there 😄 

Thank you for all your hard work!

**Comment by emplums** [comment]
Hey Nate! Great catch 😂 The library was originally called `primer-react` and we never got around to updating the homepage content afterwards it looks like!
