### ISSUE TITLE
Upgrade to styled-system v5

### ISSUE THREAD

**Issue by colebemis** [primer/components#472]
@jxnblk just released some cool new APIs and performance improvements in styled-system v5. We should upgrade :)

[Migration guide](https://styled-system.com/guides/migrating)

**Comment by jxnblk** [comment]
I started a PR, but realized you have some custom things around prop types and it took longer than five minutes. If anyone else takes a stab at this first, feel free to reach out 🙂

**Comment by colebemis** [comment]
@jxnblk I couldn't find any custom code around prop types. Is this the pattern you are referring to?

```js
Box.propTypes = {
  ...LAYOUT.propTypes,
  ...COMMON.propTypes,
  theme: PropTypes.object
}
```
https://github.com/primer/components/blob/master/src/Box.js#L13-L14

**Comment by emplums** [comment]
Will take a look at this today :) Just upgraded to v4 a couple of weeks ago!

**Comment by emplums** [comment]
done!
