### ISSUE TITLE
Add Head component for metadata

### ISSUE THREAD

**Issue by broccolini** [primer/components#478]
I’ve found myself adding this component on several websites using [React Helmet](https://github.com/nfl/react-helmet) 

Ref #100 

- [ ] test in primer.style before shipping

**Comment by emplums** [comment]
@broccolini is this referring to the actual `<head>` tag, or a visual header? I think if it's a `<head>` that should live in doctocats? Since we don't know what kind of setup people will be using Primer Components with, it might not be super useful here, and I'd like to stick to UI components for this repo

**Comment by broccolini** [comment]
> is this referring to the actual <head> tag, or a visual header?

Yes am referring to the `<head>` tag, see example here https://github.com/github/cxr/blob/componentize/src/components/Head.js

> I think if it's a <head> that should live in doctocats?

Agree this would be useful for doctocat so that people don't have to set this up from scratch every time.

> Since we don't know what kind of setup people will be using Primer Components with, it might not be super useful her

You're right that we don't know what setup people will have (for example I think Next has its own head component) so this might be better as a "website starter" component if/when we build a starter kit in future. 

> I'd like to stick to UI components for this repo

While `<head>` is not a presentational component, I do think we'll expand to include obvious and useful data components in future, however this probably isn't one of them!
