### ISSUE TITLE
TabNav component

### ISSUE THREAD

**Issue by mxstbr** [primer/components#493]
We will need a nav like this soon for our internal project (screenshot from mobile dashboard):

![Screenshot 2019-07-03 at 11 18 02](https://user-images.githubusercontent.com/7525670/60579858-3dd31b80-9d84-11e9-92ee-8c3c3b77c9e1.png)

Would there be interest in adding something like this to primer/components? I expect it should work pretty similarly to the `UnderlineNav` from an API perspective.

**Comment by emplums** [comment]
Yes, we would love something like this in Primer Components!
