### ISSUE TITLE
Button as=a renders with underlined text

### ISSUE THREAD

**Issue by LinusU** [primer/components#502]
I'm trying to render a button, like the "New issue" here on GitHub, that is also a link so that it works without JS. When doing `as='a'` I do get an extra underline that disappears when hovering the button. It would be nice if it could be styled to not have an underline by default:

```js
<ButtonPrimary as='a' href='/foo/bar'>New issue</ButtonPrimary>
```

<img width="139" alt="Screenshot 2019-07-26 at 10 47 22" src="https://user-images.githubusercontent.com/189580/61939077-c1061c80-af92-11e9-9b39-2b71ffbdcc3d.png">

**Comment by emplums** [comment]
Will go out in 13.3.0!

**Comment by LinusU** [comment]
Awesome! Thanks for the quick turn around ❤️
