### ISSUE TITLE
🐞[Bug] OutlineButton as='a' renders differently

### ISSUE THREAD

**Issue by LinusU** [primer/components#515]
<img width="162" alt="Screenshot 2019-08-05 at 18 03 20" src="https://user-images.githubusercontent.com/189580/62481800-5da69680-b7ab-11e9-80c8-5dba2b447582.png">

☝️ ordinary

👇 `as='a'`

<img width="145" alt="Screenshot 2019-08-05 at 18 03 25" src="https://user-images.githubusercontent.com/189580/62481803-5da69680-b7ab-11e9-9b50-ff2fd5dbba71.png">

```js
<ButtonOutline as='a' href='/foo'><Octicon icon={ChevronLeft} /> Issue List</ButtonOutline>
```

**Comment by albingroen** [comment]
I tried to reproduce this, but I could not:

**Chrome:**

![image](https://user-images.githubusercontent.com/19674362/79631986-bca31480-815c-11ea-8572-9f9fe6009f81.png)

**Firefox:**

![image](https://user-images.githubusercontent.com/19674362/79631994-c62c7c80-815c-11ea-8087-ab2284357773.png)

**Edge:**

![image](https://user-images.githubusercontent.com/19674362/79632008-d0e71180-815c-11ea-84c3-c2c8d7bad96b.png)

**Safari:**

![image](https://user-images.githubusercontent.com/19674362/79632024-ef4d0d00-815c-11ea-95c6-71521694e871.png)


Has this been fixed perhaps? 🤔

**Comment by LinusU** [comment]
@albingroen probably, thanks for checking 👍
