### ISSUE TITLE
Add role property to Flex.Item, flex to Flex

### ISSUE THREAD

**Issue by cheshire137** [primer/components#520]
I'm wondering if the `role` property can be added to Flex.Item, and the `flex` property to Flex. I'm using Primer components in my TypeScript app and stuck because these properties are missing:

![image (47)](https://user-images.githubusercontent.com/82317/63173461-8fb6c480-c005-11e9-8c11-669c7a0a01d5.png)
![image (48)](https://user-images.githubusercontent.com/82317/63173462-904f5b00-c005-11e9-822a-0a9c809f80aa.png)

Even just having one of these properties added would un-stick me. Thank you!

cc @emplums

**Comment by emplums** [comment]
This turned out to be because the `@types/styled-system` dependency was missing
