### ISSUE TITLE
DropdownCaret vertical alignment doesn't match primer/css

### ISSUE THREAD

**Issue by dmarcey** [primer/components#532]
It looks like the caret in the ```<Dropdown />``` is vertically too high compared to the same component in primer/css.

primer/components:
![Dropdown button where top of caret lines up with top of letter n](https://user-images.githubusercontent.com/5487287/63959483-44b39d00-ca5a-11e9-8c5a-0f03bedd66c4.png)

primer/css:
![Dropdown button where top of caret is a couple of pixels lower than the top of letter n](https://user-images.githubusercontent.com/5487287/63959513-54cb7c80-ca5a-11e9-951b-abbc3c7220af.png)

I think that this is due to the 4px transparent border that is on the bottom of the caret in the ```<Dropdown />```, which comes from ```border: ${get('space.1')}px solid transparent;```

If I add ```border-bottom-width: 0;``` to the ```<DropdownCaret />```styles, the react component matches what you see in primer/css.

Let me know if this isn't by design and I can open a PR.

**Comment by emplums** [comment]
@dmarcey this was unintentional, feel free to open a PR!

**Comment by maximilianotulian** [comment]
Hey guys, @dmarcey & @emplums, this one is available? Huge thanks

**Comment by dmarcey** [comment]
@maximilianotulian the fix will go out with 14.4.0!
#572 for tracking.

**Comment by maximilianotulian** [comment]
Thanks @dmarcey, regards!
