### ISSUE TITLE
🔮[New Component] LabelGroup

### ISSUE THREAD

**Issue by emplums** [primer/components#562]
LabelGroup - Just like there is a ButtonGroup which sets the styles when Buttons should be rendered together, we should think about something similar for Labels.
In addition to the margin between the labels, this should also flex-wrap. Here is an example of the behavior today:
![image](https://user-images.githubusercontent.com/8960591/65805466-88bdbe80-e13a-11e9-8ab7-42d2367e9bb3.png)

**Comment by emplums** [comment]
@dmarcey I've started building this out this morning, and I think in this case we should just wrap this line in a `Flex` component instead of putting the `flex-wrap` on the `LabelGroup` because in that case the user would have to put the rest of the line they want to wrap inside of `LabelGroup` which doesn't feel great! Let me know if that's what you were thinking in regards to wrapping

**Comment by dmarcey** [comment]
Yeah, I was thinking the same thing. I think that just having the margins should be good enough to start with at least. Thanks!
