### ISSUE TITLE
Cannot set borderTop on <BorderBox /> with TypeScript

### ISSUE THREAD

**Issue by dmarcey** [primer/components#576]
https://codesandbox.io/s/vigorous-bohr-rpu3s

It looks like `BorderBoxProps` doesn't extend `BorderProps`, and it probably should.

```
export interface BorderBoxProps extends CommonProps, LayoutProps, BoxProps {
    border?: string
    borderColor?: string
    borderRadius?: string | number
    boxShadow?: string
  }
```

**Comment by BinaryMuse** [comment]
Fixed by https://github.com/primer/components/pull/599, merged to 15.0.0
