### ISSUE TITLE
Theme color override in TypeScript

### ISSUE THREAD

**Issue by cheshire137** [primer/components#656]
👋 I'm trying to follow the 'Custom Theming' example from https://primer.style/components/primer-theme#custom-theming. My React app uses TypeScript. I'm getting the following error:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/82317/71635124-5a42fa00-2be7-11ea-88e4-b9d3c9599f2d.png">

It looks like including the imported Primer theme isn't adding any properties of its own:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/82317/71635146-83638a80-2be7-11ea-9868-d969f173e784.png">

I'm importing the Primer theme with `import { theme as primer } from "@primer/components";`. Could the theme be missing type definitions? Thanks!

**Comment by emplums** [comment]
The theme's type definition i just a generic `Object` and it is included in the index.d.ts file so I'm not sure what's going on here 🤔 Mind DM'ing me in Slack the repo you're trying to use this on and I will take a look?

**Comment by emplums** [comment]
Hey @cheshire137! Checked in with our resident TS expert @T-Hugs and it looks like when you modify an object, it will lose the type from the object you're spreading (`primer`). All you'd need to do in this case it create a new interface for the new modified theme like so:

```
interface Theme {[key: string] : any}

const theme: Theme = {
  ...primer,
  space: [0, 8, 16, 32, 64],
  fontSizes: [10, 12, 16, 24, 48]
}

theme.colors.bodytext = '#111'
```

**Comment by cheshire137** [comment]
Thank you!!
