### ISSUE TITLE
🔮[New Component] Menu Component

### ISSUE THREAD

**Issue by emplums** [primer/components#670]
The menu is a vertical list of navigational links. 

![image](https://user-images.githubusercontent.com/8960591/72555394-5521b400-3851-11ea-8ca1-591fd89e19cc.png)

Primer CSS: https://primer.style/css/components/navigation#menu

**Comment by albingroen** [comment]
@emplums How many levels of groups should be available? For example, Netlify has something like this:
![image](https://user-images.githubusercontent.com/19674362/79631595-aa27db80-815a-11ea-9a81-49ae4e136fbf.png)

**Comment by emplums** [comment]
@albingroen I _believe_ only one level is allowed, but let me double check with a designer and get back to you!

**Comment by emplums** [comment]
This has got me thinking, are `SideNav` and `Menu` essentially the same component?

`SideNav` can be full height and we allow nesting. In `Menu` I believe we don't allow nesting. Is it worth it to have two separate components that are visually very similar just to enforce that rule? To me, that seems more like usage guideline that we could add vs something that would warrant two separate components.

## Screenshots

In Primer CSS, it looks like `SideNav` has some more padding between items and has a grey background color instead of white:
![image](https://user-images.githubusercontent.com/8960591/80026666-5c331080-8497-11ea-8751-3b46fe323593.png)

Menu:
![image](https://user-images.githubusercontent.com/8960591/80026593-3dcd1500-8497-11ea-9a22-1a311a87eb9d.png)

But in the component refresh, I only see a mockup for a "Menu":
![image](https://user-images.githubusercontent.com/8960591/80026772-897fbe80-8497-11ea-8a9d-ae6c434a65ee.png)


Is the intention that `Menu` and `SideNav` will look the same after the refresh? Or should `SideNav` components continue to have a grey background?

cc @auareyou @broccolini @simurai

**Comment by emplums** [comment]
Hey @albingroen after chatting with the team we’ve decided to not add a separate Menu component to Primer Components since it’s so similar to SideNav 🙌 going to close this issue
