### ISSUE TITLE
🔮[New Component] Pagehead

### ISSUE THREAD

**Issue by emplums** [primer/components#671]
Adds a bottom border + some margin and padding

![image](https://user-images.githubusercontent.com/8960591/72555570-acc01f80-3851-11ea-8eaa-18ca12cb1c39.png)

https://primer.style/css/components/pagehead

**Comment by taylorcjohnson** [comment]
I can volunteer for this one if still up for grabs. Should this first iteration of the Pagehead component only include the bottom border and spacing for any provided child component or should it also include sub components for pagehead actions, org nav, and Repohead listed in the Primer CSS entry?
