### ISSUE TITLE
🔮 [New Component] Pagination

### ISSUE THREAD

**Issue by emplums** [primer/components#672]
Use the pagination component to apply button styles to a connected set of links that go to related pages (for example, previous, next, or page numbers).

Previous/Next:
![image](https://user-images.githubusercontent.com/8960591/72555636-d416ec80-3851-11ea-93eb-26dcf4fac454.png)

Numbered:
![image](https://user-images.githubusercontent.com/8960591/72555647-db3dfa80-3851-11ea-8ef0-26078d622b81.png)

API:
- Should be able to just render prev/next buttons OR add numbered buttons to them
- Each numbered button should have a link (not sure how we will pass this data cleanly 🤔 )

**Comment by BinaryMuse** [comment]
I wonder if it would be worth taking a look at something like https://github.com/AdeleD/react-paginate

**Comment by BinaryMuse** [comment]
Closed by #739
