### ISSUE TITLE
🔮[New Component] Side Nav

### ISSUE THREAD

**Issue by emplums** [primer/components#675]
The Side Nav is a vertical list of navigational links, typically used on the left side of a page. 

![image](https://user-images.githubusercontent.com/8960591/72556123-d75ea800-3852-11ea-9fb3-7171517b7e9c.png)

https://primer.style/css/components/navigation#side-nav

**Comment by thebiltheory** [comment]
✋

**Comment by BinaryMuse** [comment]
Closed by #695
