### ISSUE TITLE
🔮 [New Component] ProgressBar

### ISSUE THREAD

**Issue by emplums** [primer/components#676]
Use Progress components to visualize task completion. The Progress class adds a background color and aligns its children horizontally with flexbox. The children should be individually colored with background utilities and sized with inline width styles in percentages. Overflow is hidden, so children that overflow will be clipped.

![image](https://user-images.githubusercontent.com/8960591/72556214-02e19280-3853-11ea-9145-22a4a55b1021.png)

https://primer.style/css/components/progress

**Comment by BinaryMuse** [comment]
Is this a dup of #560?

**Comment by BinaryMuse** [comment]
https://primer.style/components/ProgressBar exists so closing this 🤷‍♀
