### ISSUE TITLE
📒[Docs] Explore new development environment

### ISSUE THREAD

**Issue by emplums** [primer/components#680]
We've chatted a bunch about creating a new environment for development of components, right now we're doing everything in the docs. I propose that we give Storybook a try - my main motivations for using storybook are:
- minimal set up time (vs building our own environment/tool)
- many people are already familiar with Storybook
- Makes visual regression testing easier :) 

### Must Have
- [ ] Base stories for each component

### Nice to Have
- [ ] Variations for each component
- [ ] Viewport addon
- [ ] Custom theme for storybook shell using Primer Theme
- [ ] Ability to see docs side by side without duplicating the docs content
- [ ] Some way for developers to interact with props - either Knobs or a live code editor. It looks like Knobs doesn't work well with styled-system so that might be out of the picture!

**Comment by BinaryMuse** [comment]
I'm 👍 for starting with Storybook

**Comment by emplums** [comment]
@BinaryMuse cool beans - I started setting it up today! :) Will finish up tomorrow and make a PR

**Comment by yaili** [comment]
@emplums This is in Done, can it closed? 🙂
