### ISSUE TITLE
Docs "style-system border docs" link is incorrect

### ISSUE THREAD

**Issue by nombrekeff** [primer/components#688]
Hey there! Just found an incorrect link in the docs, located in [this](https://primer.style/components/system-props) link.

It's the **"style-system border docs"** link show in this image:
![image](https://user-images.githubusercontent.com/17043260/73976650-0a173000-4929-11ea-8111-3a40c7668af4.png)

The current link is: `.../docs/table.md#misc`
Should be: `.../docs/table.md#border`

**Comment by emplums** [comment]
Thank you! Fixed in #689 :)

**Comment by nombrekeff** [comment]
Wow, blazing!! Thanks!
