### ISSUE TITLE
[Bug] Page unclickable after side-nav collapse

### ISSUE THREAD

**Issue by gc** [primer/components#691]
Hi friends, I think I found a little bug in the documentation website, which results in the page becoming unclickable.

**Reproduction Steps:**
Step 1. Open https://primer.style/components/ on PC
Step 2. Resize window until hamburger menu on top-right appears, then click on it.
Step 3. Without pressing anything else, resize the window back wide enough that the hamburger menu disappears, the page is now unclickable, unscrollable, etc.

**Comment by BinaryMuse** [comment]
Thanks for the bug report. This is fixed for Primer Components; I'll be rolling the fix out to the other sections of primer.style throughout the day.
