### ISSUE TITLE
Heading docs are misleading / confusing

### ISSUE THREAD

**Issue by BinaryMuse** [primer/components#694]
The docs for the `Heading` component say:

> The Heading component will render an html h1-6 tag without any default styling.

However, this component always renders a `h1` unless the user passes `as="h2"` etc, which is not made explicit in the docs. We should:

1. Change `Heading` to default to `h2` so users don't accidentally use multiple `h1`s
2. Update the docs to be clear on how to choose a different heading level

**Comment by taylorcjohnson** [comment]
Hello, if you’re open to new contributors I would like to volunteer for this issue! This would be my first contribution to Primer, but the guidelines look straight-forward.

**Comment by emplums** [comment]
Done!
