### ISSUE TITLE
TextInput onChange handler?

### ISSUE THREAD

**Issue by jannekauppila** [primer/components#698]
I see a ticket has been closed on TextInput onChange handler (https://github.com/primer/components/issues/127), but I can't see onChange on TextInput. Am I missing something?

**Comment by dmarcey** [comment]
Can you check out this code sandbox and see if it works for you?
https://codesandbox.io/s/brave-forest-k57lb

If you're referring to the fact that it's not in the documentation, we decided not to list all of the underlying `<input />` props in the docs, and just put a message that:

![image](https://user-images.githubusercontent.com/5487287/75156554-5c55a080-56e0-11ea-8e72-99d15684f739.png)

Let us know if that doesn't resolve your issue.

**Comment by jannekauppila** [comment]
It works indeed! I'm sorry, I thought I did try it - apparently I didn't.
