### ISSUE TITLE
[BUG] Dropdown has unwanted style duplication

### ISSUE THREAD

**Issue by clayplumridge** [primer/components#705]
Repro:
Create a `<Dropdown mr={1} />`
Inspect the `details` and `summary` elements produced
You'll see that the margin is applied to both, resulting in double the desired margin.

**Comment by BinaryMuse** [comment]
Good catch, thanks for the bug report. The `rest` [is indeed spread](https://github.com/primer/components/blob/master/src/Dropdown.js#L12-L14) onto both the `Details` and `Button`.

@emplums, do you think we should split these two items into separate components (similar to `SideNav.Link`)?

**Comment by emplums** [comment]
@BinaryMuse yeah - I think we need to do a pretty big refactor to Dropdown, I don't think that the way it's set up right now is flexible enough for most use cases. I'll keep this in mind when I start the refactor 🙌
