### ISSUE TITLE
Invalid display attributes being passed in docs

### ISSUE THREAD

**Issue by gc** [primer/components#709]
I was browsing the docs source to see how the side menu is done, and I noticed this:
![image](https://user-images.githubusercontent.com/30398469/76467932-ddca6400-643e-11ea-9acf-b76a2578341e.png)

Looks like a bug? It occurs wherever this is coded:
![image](https://user-images.githubusercontent.com/30398469/76467976-f0449d80-643e-11ea-8177-34fdc4b59936.png)

**Comment by emplums** [comment]
Hey @gc thanks for the issue! This would fall under the [Primer Doctocat repo](https://github.com/primer/doctocat), but I think this is just a matter of how styled-components filters out props to pass down as attributes to the DOM - there some more information about how/why this happens on the [styled-system docs here](https://styled-system.com/guides/removing-props-from-html/) if you'd like to check it out!
