### ISSUE TITLE
Button Component Z-Index and Click Events Issue in v13.2.0

### ISSUE THREAD

**Issue by acknosyn** [primer/components#711]
I'm having an issue with the Button component in version `13.2.0`.

The issue starts happening in `@primer/components` version `13.2.0`, the issue is not present in version `13.1.0`. Unfortunately, the issue is still present in the latest version, `16.0.0`.

When the Button component is clicked, the button element disappears behind all other elements (you can tell by lowering the menu's opacity). The z-index is unchanged in the CSS, so it could be a rendering bug. The button has the highest z-index on the page, so it should always stay on top of other elements.

Clicking another time brings the element forward again; even clicking in the developer tools window, outside of the rendered view (as shown in the GIFs).

When the menu opens, click events on the button are ignored until the menu is moved out of view. The menu has a z-index lower than the button, but it appears it could be blocking the click events. 

The button is listening for click events to open and close the menu. The menu doesn't close when clicking the button with the menu open.

---

Here are GIF previews of the issue:

### 1. Button component issue.

`@primer/components` version: `13.2.0`

Button component disappears behind other elements and click events are ignored.

![Primer_Components_Button_Not_Working_v13 2 0](https://user-images.githubusercontent.com/8602276/76692623-e8def780-66bd-11ea-9a39-d59fbc917f3e.gif)

### 2. Button component working as expected.

`@primer/components` version: `13.1.0`

Button component stays on top of menu and click events are captured.

![Primer_Components_Button_Working_v13 1 0](https://user-images.githubusercontent.com/8602276/76692625-f0060580-66bd-11ea-9e85-3ecb0b4eb180.gif)

---

I've uploaded a test repo demonstrating the issue. It's a default GatsbyJS app with `@primer/components` and `styled-components`. Install instructions are in the README.

https://github.com/acknosyn/Testing-Primer-Components

Thanks for your help.

**Comment by emplums** [comment]
Hey @acknosyn thanks for bringing this to our attention! It looks like some z-index got added on focus for Buttons in the 13.2.0 release - I wrote up some notes in my PR fixing this but still have a bit more digging to do before I feel comfortable shipping the change. Should have it out sometime early next week! :)

**Comment by emplums** [comment]
Thanks a ton for the test environment too, that was super helpful! 🙌 💖

**Comment by acknosyn** [comment]
Hey @emplums, thanks a ton for the quick response! So glad to hear you know what the issue is. 😄

Good to know the extra effort was helpful haha. I wanted to make sure this was as clear as possible and easy to replicate. 

Looking forward to the update. 👌
