### ISSUE TITLE
@primer/components has no exported member Grid

### ISSUE THREAD

**Issue by JerryGreen** [primer/components#718]
<img width="899" alt="Screenshot 2020-03-17 at 11 11 37" src="https://user-images.githubusercontent.com/13215662/76827177-15228180-6840-11ea-9a04-28b33efb7b0a.png">

The issue here, - the type definitions are missing. There's actual code for Grid, it somehow works. But no types.

P.S. I'm using `16.0.0` version of @primer/components

**Comment by emplums** [comment]
oof, thanks for the heads up @JerryGreen! I'll get a fix in the minor release tomorrow

**Comment by emplums** [comment]
This was shipped 🙌
