### ISSUE TITLE
Dialog changes

### ISSUE THREAD

**Issue by emplums** [primer/components#730]
Let's make the `Dialog` component a bit more flexible with content. Right now, it always renders a grey header at the top of the component - I propose we make that optional or a sub component of Dialog, so that teams who have a bit of a different look can still use `Dialog`

**Comment by emplums** [comment]
To avoid a breaking change, we could do something like having a prop called `noHeader` - but I'm also not opposed to shipping a breaking change for this one either

**Comment by BinaryMuse** [comment]
Closed by #736
