### ISSUE TITLE
isProcessing prop for the button components

### ISSUE THREAD

**Issue by albingroen** [primer/components#770]
A feature that many component libraries have on their button component is some sort of prop for showing that the button is loading. For example `isProcessing` or `isLoading`. This can be really useful in cases like submitting a form and waiting for the mutation to finish.

## All button components
| Name | Type | Default | Description |
| :- | :- | :-: | :- |
| ... | ... | ... | ... |
| isProcessing | Boolean | false | displaying if the button is in a loading state or not |

**Comment by emplums** [comment]
Hey @albingroen! I think we will hold off any adding anything like this for now as we don't have any type of loading states in buttons in our Design System and don't have plans for anything like that in the near future
