### ISSUE TITLE
[🐞 Bug] `SelectMenu` position issue

### ISSUE THREAD

**Issue by albingroen** [primer/components#792]
# Issue
When using the `SelectMenu` component, for some reason the menu part jumps down to a completely unwanted page.

# Code
```javascript
  <SelectMenu aria-label={ariaLabel}>
    <Button as="summary">
      {title}{' '}
      <i style={{ marginLeft: '0.75rem' }}>
        <FontAwesomeIcon icon={faCaretDown} />
      </i>
    </Button>
    <SelectMenu.Modal>
      {options.map((optionGroup: IOptionGroup) => (
        <React.Fragment key={optionGroup.key}>
          <SelectMenu.Header>{optionGroup.title}</SelectMenu.Header>
          <SelectMenu.List>
            {optionGroup.options.map((option: IOption) => (
              <SelectMenu.Item
                onClick={() => onChange(option.value)}
                selected={option.value === value}
                key={option.value}
              >
                {option.text}
              </SelectMenu.Item>
            ))}
          </SelectMenu.List>
        </React.Fragment>
      ))}
    </SelectMenu.Modal>
  </SelectMenu>
```

# Image
![image](https://user-images.githubusercontent.com/19674362/80891841-f4ff3280-8cc6-11ea-995d-e4565aaa386e.png)

# Gif
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/19674362/80891941-a69e6380-8cc7-11ea-91fd-9c5e3fcd33b7.gif)

# Browser: Chrome

**Comment by albingroen** [comment]
This has something to do with the container I wrapped my app in. I did some overflow auto stuff, and when removing all of that this does not longer occur.

**Comment by emplums** [comment]
Going to close this one as I believe it has to do with how the wrappers were positioned/overflowed in this case! :) I added some documentation about this in the last release
