### ISSUE TITLE
Add `block` or `width` prop to `Button` component

### ISSUE THREAD

**Issue by albingroen** [primer/components#793]
# Feature request

It would be really nice if there was a easy way to make any `Button` component span the entire parent. Either by adding a `block` prop like on the `TextInput` component or a `width` prop like on many other components.

**Comment by emplums** [comment]
Hey @albingroen! The `Button` component does have access to the `width` prop, though it looks like we forgot to update the docs when we added it. Going to close this in favor of a PR that updates the docs.



This should work:
`<Button width="100%">Button</Button>`

**Comment by albingroen** [comment]
@emplums Hmm okay I see, although might there be some ts type missing there? Because ts won't let me enter a `width` prop on any button component 🤔
