### ISSUE TITLE
SelectMenu navigation

### ISSUE THREAD

**Issue by emplums** [primer/components#799]
Currently, if a user opens the select menu using their mouse, we allow them to navigate using tabs. But if they open the select menu using their keyboard, they can navigate using the up/down arrows as per the wcag spec. Should the behaviour be the same regardless of whether they opened using a mouse or a keyboard?

Creating this issue because I honestly don't remember the decision making process behind this when I built this 😂cc @muan if you have any thoughts! I believe the keyboard nav we implemented here was based off of the WS work in `details-menu` here: https://github.com/github/details-menu-element/blob/master/index.js#L217

**Comment by dmarcey** [comment]
As a data point (not guaranteeing this is correct, but it did go through an accessibility audit), the Azure Dev Ops `<Dropdown />` used only arrow keys once you opened the dropdown.

https://developer.microsoft.com/en-ca/azure-devops/components/dropdown#advanced-dropdown

So, when expanding by activating the button, the filter `<input />` gets focus. Then the user can down arrow to move to the tabs (right and left arrow to move between the tabs) and down arrow again to get to the items. Tabbing at any point will close the menu and return focus to the button.

At the very least it seems like maybe left/right arrow should be able to move focus between the tabs?
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html

**Comment by muan** [comment]
`<details-menu>`'s arrow key navigation works regardless how the menu is opened.  We follow https://www.w3.org/TR/wai-aria-practices-1.2/#menu. The cases with input is slightly different.

**Comment by fregante** [comment]
I'll hijack this to suggest supporting navigating by typing as well, as available on macOS (and presumably on other OSes as well). Example when pressing <kbd>g</kbd>:


![](https://user-images.githubusercontent.com/1402241/100029978-18e7aa00-2db8-11eb-88fd-07eb1d45fc05.gif)

**Comment by emplums** [comment]
I believe this has been addressed!
