### ISSUE TITLE
Button is not honoring backgroundColor prop

### ISSUE THREAD

**Issue by dmarcey** [primer/components#818]
With `@primer/components@19.0.0` the `<Button />` component appears to ignore the `backgroundColor` prop.

```
<Button backgroundColor="green.4">Click me</Button>
```

However, the `sx` prop seems to work.

```
<Button ml={2} sx={{ backgroundColor: "green.4" }}>
    Click me
</Button>
```

**Code sandbox repro**
https://codesandbox.io/s/tender-sutherland-7p356?file=/src/App.js

It seems like the prop is being overridden by the defaults:

![image](https://user-images.githubusercontent.com/5487287/83054414-60b39180-a020-11ea-9555-dde2a4c332aa.png)

**Comment by emplums** [comment]
Fixed in 19.1.0! 🎉
