### ISSUE TITLE
Focus color mobile 

### ISSUE THREAD

**Issue by saihaj** [primer/components#837]
On mobile when you click the nav menu and close it then the color of `ThreeBarsIcon` stays same as hover color until you focus somewhere else. Is there a way to fix it?

![CECB472A-8451-4D73-A5C5-9B0D6168CF3E](https://user-images.githubusercontent.com/44710980/85175941-45fac400-b23e-11ea-93e9-1713200f9b2b.gif)

**Comment by emplums** [comment]
Hey @saihaj do you mind opening this issue in our https://github.com/primer/doctocat repo? That's the repo that handles the styling for all of our documentation sites :)
