### ISSUE TITLE
🗣[Discussion] Remove dividers on github.com dashboard

### ISSUE THREAD

**Issue by albingroen** [primer/components#838]
> I'm not sure if this is the place to add this issue. It's maybe more of GitHub domain design thing, although I don't really know where else to put it.

Here's my 2 cents:

Problem: **Dividers between the notifications on the dashboard is unnecessary** and just clutters the design in my opinion.
Solution: Remove the dividers and add more margin/padding between the notifications instead.

![Screenshot 2020-06-23 at 21 55 14](https://user-images.githubusercontent.com/19674362/85454928-b470b680-b59d-11ea-8599-e38145e2f224.png)

Please forward this to the right place if this is not the one 🙂

**Comment by emplums** [comment]
Thanks for your feedback! Unfortunately this is not something we can address in Primer. Please contact support so that they can follow this up with the relevant team at GitHub 🙌  https://support.github.com/contact
