### ISSUE TITLE
🐞 [Bug] Misaligned emoji badge

### ISSUE THREAD

**Issue by albingroen** [primer/components#839]
The status badge on a profile picture seem to be misaligned.

![Screenshot 2020-06-23 at 22 34 58](https://user-images.githubusercontent.com/19674362/85459215-36fb7500-b5a2-11ea-919a-b4f9ae223379.png)

**Comment by emplums** [comment]
Hey @albingroen is this specific to Primer Components or is this a bug report for GitHub.com?

**Comment by emplums** [comment]
Confirmed this looks like a GitHub.com bug that's been resolved. If you're still seeing it, feel free to file a bug report with support: https://support.github.com/contact
