### ISSUE TITLE
Tooltip works poorly in Safari

### ISSUE THREAD

**Issue by JerryGreen** [primer/components#859]
I've just tried official Tooltip example:

https://primer.style/components/Tooltip

It works perfectly in Chrome, but here's what I've got in Safari:

> <p align="center"><img src="https://user-images.githubusercontent.com/13215662/90303743-0660f900-deca-11ea-81bb-9c8e957cb998.gif" width="320" height="130"/></p>

It seems it works only once, then doesn't show again (until you refresh the page).

**Comment by emplums** [comment]
Thanks for the heads up @JerryGreen! I have a hunch this might have something to do with our docs site, but will double check when I take a look at this

**Comment by emplums** [comment]
@JerryGreen do you mind sharing what version of Safari you're on? I'm having a hard time reproducing on my end

**Comment by diakonos** [comment]
I see this too, on Safari Version 13.1.2 (15609.3.5.1.3).

**Comment by JerryGreen** [comment]
I tried it on recently updated Safari, Version 14.0 (15610.1.28.1.9, 15610), and it seems to be working good now
