### ISSUE TITLE
Enable/disable buttons

### ISSUE THREAD

**Issue by samuela** [primer/components#861]
Based on https://primer.style/components/Buttons, it doesn't seem like there's a way to do a disable a button. Is there a prop for this?

**Comment by samuela** [comment]
Also same thing for `TextInput`

**Comment by samuela** [comment]
Update: `Button` has a `disabled` prop. It's just not in the docs.

**Comment by emplums** [comment]
Hey @samuela! We don't tend to add native attributes to the props tables, which is why they are missing for both the input and button components!
