### ISSUE TITLE
SubNav.Links not available in TypeScript

### ISSUE THREAD

**Issue by cheshire137** [primer/components#872]
👋 I'm getting an error trying to follow the example on https://primer.style/components/SubNav which includes a `<SubNav.Links>` element:

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/82317/93006529-d76a9100-f522-11ea-83b7-46dd068a22e7.png">

I'm using `@primer/components` version 19.1.1.

**Comment by emplums** [comment]
Thanks for the heads up! I'll fix this next week!

**Comment by pavelkeyzik** [comment]
@emplums May I take this one?

**Comment by emplums** [comment]
whoops @pavelkeyzik just saw this! I just pushed up a PR to fix this, but thank you!

**Comment by pavelkeyzik** [comment]
@emplums No worries 😄
