### ISSUE TITLE
Broken reference "Edit this page on GitHub".

### ISSUE THREAD

**Issue by x-N0** [primer/components#876]
This is the broken reference:
https://github.com/primer/components/edit/master/docs/content/index.md

Site:
https://primer.style/components/
You can see this link at the bottom of the page.

Did you changed the scaffolding?
If so, others links might be broken too.

**Comment by x-N0** [comment]
Found the file:
https://github.com/primer/components/blob/main/docs/content/index.md

**Comment by yaili** [comment]
@emplums Think this is from renaming `master` to `main` https://github.com/primer/components/commit/2fb05d97f1db79f82f15d860c5b5f034938208fd - we need to update all the "edit" links.

**Comment by emplums** [comment]
Ooh nice catch @x-N0 @yaili I will fix this up this morning :)
