### ISSUE TITLE
href attribute missing for HeaderLinkProps in TypeScript

### ISSUE THREAD

**Issue by cheshire137** [primer/components#893]
I was following the example on https://primer.style/components/Header in my TypeScript app, but I'm not able to set the `href` attribute on `Header.Link`:

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/82317/97789929-5af34680-1b92-11eb-9394-0de703f76756.png">

> Type '{ children: Element; href: string; fontSize: number; }' is not assignable to type 'IntrinsicAttributes & HeaderLinkProps & { children?: ReactNode; }'.
  Property 'href' does not exist on type 'IntrinsicAttributes & HeaderLinkProps & { children?: ReactNode; }'. Did you mean 'ref'?

Specifically, it was this line that had the error: `<Header.Link href="#" fontSize={2}>`

I'm using version 20.3.0 of `@primer/components`.

**Comment by emplums** [comment]
Fixed in 22.0.0! 🎉
