### ISSUE TITLE
Inconsistent typing for Dropdown component

### ISSUE THREAD

**Issue by joelalejandro** [primer/components#954]
**Describe the bug**
Following [the default example implementation](https://primer.style/components/Dropdown#default-example), the Dropdown component cannot be used as described in the documentation when using TypeScript, due to inconsistencies between what the documentation states and how the Dropdown component is currently typed.

**To Reproduce**
1. In a `.tsx` file, copy and paste the example code from the Dropdown documentation page.
2. See your IDE marking required property errors.

**Expected behavior**
Apparently, this behaviour is caused due to the definition of `DropdownProps` as a direct extension of `DetailsProps`:

```ts
export interface DropdownProps extends DetailsProps {}
```

This can be fixed using `Partial<DetailsProps>` if there is a real interest in keeping both definitions in sync.

A possible definition could also be:

```ts
export interface DropdownProps {
  open?: boolean;
  defaultOpen?: boolean;
  onToggle?: (event: React.SyntheticEvent<HTMLDetailsElement>) => void;
  onClickOutside?: (event: React.MouseEvent) => void
  overlay?: boolean;
}
``` 

**Screenshots**
![image](https://user-images.githubusercontent.com/118913/103371399-1a3e7d80-4aae-11eb-86f0-fd5c57b6f9d1.png)

**Comment by ilomon10** [comment]
now it onClickOutside doesn't work by default even overlay is true (duplicate #807 )

**Comment by emplums** [comment]
This should be fixed now, let me know if you continue to have issues
