### ISSUE TITLE
Width prop not pulling from spacing scale

### ISSUE THREAD

**Issue by emplums** [primer/components#958]
**Describe the bug**
Today I noticed that when doing something like: 

`<Box width={3}/>`

I would expect the `3` here to pull the 3rd value from our spacing scale. Instead, the generated CSS is `width: 3px`

**To Reproduce**
1. https://primer.style/components/Box
2. Edit the width in one of the examples to be `width={3}`
3. See that it makes the width only 3 pixels instead of the expected 16px

**Expected behavior**
Width system prop should pull from spacing scale in the theme

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by colebemis** [comment]
Looks like this is not a bug. The `width` prop references `sizes` theme field: https://styled-system.com/table#layout
